### ISSUE TITLE
Report: Cannot complete clear quests

### ISSUE THREAD

**Issue by vbnet3d** [vbnet3d/SpawnSleepersInRange#1]
Some people reported not being able to complete clear quests with this mod.

Examples are needed.

**Comment by SaL1ow** [comment]
someone says some zombies still need press the button to spawn,hope that can help u.

**Comment by vbnet3d** [comment]
Reproduced this in Mobile Field Hospital (tier 3). The final set of zombies is spawned in only by trigger after the explosion of some barrels. The POI can be cleared by enabling triggers again. Looking now for a workaround that allows specific kinds of triggers like these to still be run while general volume triggers get skipped.
