### ISSUE TITLE
Does not seem to work upon re-entry

### ISSUE THREAD

**Issue by InkyCricket** [vbnet3d/SpawnSleepersInRange#3]
When a sleeper spawns but then later despawns because the player is too far away or just passing through, they do not spawn again until the player gets extremely close.

![20240918201548_1](https://github.com/user-attachments/assets/80396614-f3af-4dd2-83b7-d11cfdb6d773)
The wooden boxes on the left are where I was when the zombies in that cage first spawned, and I think that's the border of the poi. 

The boxes on the right are how close I need to get to make them spawn after I leave the area and return, and if I re-approach the poi from the roof instead they don't respawn until I jump down to almost ground level. 

This poi, used as the example, is store_hardware_03. Sorry I had one other mod, one that hides poi names and ratings, so it didn't show up in the screenshot. 

Config, in case it matters:
```
<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <UseSplitSpawnRadii>true</UseSplitSpawnRadii>
  <SpawnRadius>30</SpawnRadius>
  <VerticalSpawnRadius>10</VerticalSpawnRadius>
  <DisableTriggers>true</DisableTriggers>
  <SpawnAggressive>false</SpawnAggressive>
  <AllowClearQuestTriggers>false</AllowClearQuestTriggers>
  <OnlySpawnInCurrentPOI>true</OnlySpawnInCurrentPOI>
  <UpdateAfterTicksInterval>30</UpdateAfterTicksInterval>
</Config>
```

**Comment by vbnet3d** [comment]
@InkyCricket can you retry this with the UpdateAfterTicksInterval made much smaller? Like 1 or 2? Depending on the frequency of checks I could see it being just outside the range on the first check and then not hitting again until you've moved much closer.

I see one potential cause for this but I'd like to rule out the update rate first.

**Comment by InkyCricket** [comment]
@vbnet3d 
UpdateAfterTicksInterval has been set to 1 and all other mods uninstalled except this one.

The behavior remains unchanged.

**Comment by vbnet3d** [comment]
@InkyCricket thanks for the feedback. I've pushed a change that seems to fix this issue. Please let me know if it resolves it for you.

**Comment by InkyCricket** [comment]
Thank you very much.

It is still spotty.

I set my config to this, just for now:

```<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <UseSplitSpawnRadii>true</UseSplitSpawnRadii>
  <SpawnRadius>45</SpawnRadius>
  <VerticalSpawnRadius>100</VerticalSpawnRadius>
  <DisableTriggers>true</DisableTriggers>
  <SpawnAggressive>false</SpawnAggressive>
  <AllowClearQuestTriggers>false</AllowClearQuestTriggers>
  <OnlySpawnInCurrentPOI>false</OnlySpawnInCurrentPOI>
  <UpdateAfterTicksInterval>15</UpdateAfterTicksInterval>
  <ActivateTriggersAtRange>true</ActivateTriggersAtRange>
</Config>
```

Only 2 of the 4 sleepers in the poi have spawned. These two spawn in at a nice distance away, even if I am super high up.

![image](https://github.com/user-attachments/assets/27e2177d-5ab6-473e-a4b9-eff103765fc9)

These other two zombies refuse to spawn until I move almost to ground level and get close to the trailers they are in:

![image](https://github.com/user-attachments/assets/a21f20bf-b751-4567-846d-391770df0faa)

**Comment by vbnet3d** [comment]
@InkyCricket thanks. The UpdateAfterTicksInterval method was the culprit. It was apparently sharing the same counter between all Sleeper Volumes, leading to situations where some would not get updated for a while. I attempted tying it to each instance, but that was also inconsistent. Since it was an experimental optimization without proven benefit, I'm removing it so the experience will be consistent.
